name: Package

on: workflow_dispatch

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and Push Base
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: |
            platipy/platipy:latest
            ghcr.io/pyplati/platipy:latest
      -
        name: Build and Push Cardiac
        uses: docker/build-push-action@v2
        with:
          context: platipy/imaging/projects/cardiac
          platforms: linux/amd64
          push: true
          tags: |
            platipy/platipy:cardiac
            ghcr.io/pyplati/platipy:cardiac
      -
        name: Build and Push Bronchus
        uses: docker/build-push-action@v2
        with:
          context: platipy/imaging/projects/bronchus
          platforms: linux/amd64
          push: true
          tags: |
            platipy/platipy:bronchus
            ghcr.io/pyplati/platipy:bronchus
  